package neu.edu.entity;
// Generated Apr 27, 2017 1:40:37 AM by Hibernate Tools 5.2.1.Final

/**
 * DonorServices generated by hbm2java
 */
public class DonorServices implements java.io.Serializable {

	private Integer donorServicesId;
	private UserAccount userAccount;
	private UserServices userServices;
	private String cardNo;
	private Integer cvv;
	private String expiry;

	public DonorServices() {
	}

	public DonorServices(UserServices userServices) {
		this.userServices = userServices;
	}

	public DonorServices(UserAccount userAccount, UserServices userServices, String cardNo, Integer cvv,
			String expiry) {
		this.userAccount = userAccount;
		this.userServices = userServices;
		this.cardNo = cardNo;
		this.cvv = cvv;
		this.expiry = expiry;
	}

	public Integer getDonorServicesId() {
		return this.donorServicesId;
	}

	public void setDonorServicesId(Integer donorServicesId) {
		this.donorServicesId = donorServicesId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public UserServices getUserServices() {
		return this.userServices;
	}

	public void setUserServices(UserServices userServices) {
		this.userServices = userServices;
	}

	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public Integer getCvv() {
		return this.cvv;
	}

	public void setCvv(Integer cvv) {
		this.cvv = cvv;
	}

	public String getExpiry() {
		return this.expiry;
	}

	public void setExpiry(String expiry) {
		this.expiry = expiry;
	}

}
