package neu.edu.entity;
// Generated Apr 26, 2017 11:56:41 PM by Hibernate Tools 5.2.1.Final

/**
 * ProjectDeleteReasonId generated by hbm2java
 */
public class ProjectDeleteReasonId implements java.io.Serializable {

	private int projectId;
	private String reason;
	private String comments;

	public ProjectDeleteReasonId() {
	}

	public ProjectDeleteReasonId(int projectId) {
		this.projectId = projectId;
	}

	public ProjectDeleteReasonId(int projectId, String reason, String comments) {
		this.projectId = projectId;
		this.reason = reason;
		this.comments = comments;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectDeleteReasonId))
			return false;
		ProjectDeleteReasonId castOther = (ProjectDeleteReasonId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& ((this.getReason() == castOther.getReason()) || (this.getReason() != null
						&& castOther.getReason() != null && this.getReason().equals(castOther.getReason())))
				&& ((this.getComments() == castOther.getComments()) || (this.getComments() != null
						&& castOther.getComments() != null && this.getComments().equals(castOther.getComments())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + (getReason() == null ? 0 : this.getReason().hashCode());
		result = 37 * result + (getComments() == null ? 0 : this.getComments().hashCode());
		return result;
	}

}
