package neu.edu.entity;
// Generated Apr 25, 2017 11:18:45 AM by Hibernate Tools 5.2.1.Final

/**
 * ProjectService generated by hbm2java
 */
public class ProjectService implements java.io.Serializable {

	private Integer serviceId;
	private UserProjects userProjects;
	private String serviceAmount;
	private String serviceDesc;
	private String serviceStatus;

	public ProjectService() {
	}

	public ProjectService(UserProjects userProjects) {
		this.userProjects = userProjects;
	}

	public ProjectService(UserProjects userProjects, String serviceAmount, String serviceDesc, String serviceStatus) {
		this.userProjects = userProjects;
		this.serviceAmount = serviceAmount;
		this.serviceDesc = serviceDesc;
		this.serviceStatus = serviceStatus;
	}

	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	public UserProjects getUserProjects() {
		return this.userProjects;
	}

	public void setUserProjects(UserProjects userProjects) {
		this.userProjects = userProjects;
	}

	public String getServiceAmount() {
		return this.serviceAmount;
	}

	public void setServiceAmount(String serviceAmount) {
		this.serviceAmount = serviceAmount;
	}

	public String getServiceDesc() {
		return this.serviceDesc;
	}

	public void setServiceDesc(String serviceDesc) {
		this.serviceDesc = serviceDesc;
	}

	public String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

}
