package neu.edu.entity;
// Generated Apr 27, 2017 1:40:37 AM by Hibernate Tools 5.2.1.Final

/**
 * ProjectDeleteReason generated by hbm2java
 */
public class ProjectDeleteReason implements java.io.Serializable {

	private Integer projectDeleteReasonId;
	private UserProjects userProjects;
	private String reason;
	private String comments;

	public ProjectDeleteReason() {
	}

	public ProjectDeleteReason(UserProjects userProjects) {
		this.userProjects = userProjects;
	}

	public ProjectDeleteReason(UserProjects userProjects, String reason, String comments) {
		this.userProjects = userProjects;
		this.reason = reason;
		this.comments = comments;
	}

	public Integer getProjectDeleteReasonId() {
		return this.projectDeleteReasonId;
	}

	public void setProjectDeleteReasonId(Integer projectDeleteReasonId) {
		this.projectDeleteReasonId = projectDeleteReasonId;
	}

	public UserProjects getUserProjects() {
		return this.userProjects;
	}

	public void setUserProjects(UserProjects userProjects) {
		this.userProjects = userProjects;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
