package neu.edu.entity;
// Generated Apr 27, 2017 1:40:37 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserServices generated by hbm2java
 */
public class UserServices implements java.io.Serializable {

	private Integer serviceId;
	private UserProjects userProjects;
	private Double serviceAmount;
	private String serviceDesc;
	private Date serviceEndDate;
	private Set donorServiceses = new HashSet(0);

	public UserServices() {
	}

	public UserServices(UserProjects userProjects) {
		this.userProjects = userProjects;
	}

	public UserServices(UserProjects userProjects, Double serviceAmount, String serviceDesc, Date serviceEndDate,
			Set donorServiceses) {
		this.userProjects = userProjects;
		this.serviceAmount = serviceAmount;
		this.serviceDesc = serviceDesc;
		this.serviceEndDate = serviceEndDate;
		this.donorServiceses = donorServiceses;
	}

	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	public UserProjects getUserProjects() {
		return this.userProjects;
	}

	public void setUserProjects(UserProjects userProjects) {
		this.userProjects = userProjects;
	}

	public Double getServiceAmount() {
		return this.serviceAmount;
	}

	public void setServiceAmount(Double serviceAmount) {
		this.serviceAmount = serviceAmount;
	}

	public String getServiceDesc() {
		return this.serviceDesc;
	}

	public void setServiceDesc(String serviceDesc) {
		this.serviceDesc = serviceDesc;
	}

	public Date getServiceEndDate() {
		return this.serviceEndDate;
	}

	public void setServiceEndDate(Date serviceEndDate) {
		this.serviceEndDate = serviceEndDate;
	}

	public Set getDonorServiceses() {
		return this.donorServiceses;
	}

	public void setDonorServiceses(Set donorServiceses) {
		this.donorServiceses = donorServiceses;
	}

}
