package neu.edu.entity;
// Generated Apr 27, 2017 1:40:37 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserProjects generated by hbm2java
 */
public class UserProjects implements java.io.Serializable {

	private Integer projectId;
	private UserAccount userAccount;
	private UserCategory userCategory;
	private String projectName;
	private String projectDesc;
	private Date createdOn;
	private String projectStatus;
	private Double projectAmount;
	private Date endDate;
	private Double remainingAmount;
	private Set userServiceses = new HashSet(0);
	private Set projectDeleteReasons = new HashSet(0);

	public UserProjects() {
	}

	public UserProjects(String projectName, Date createdOn) {
		this.projectName = projectName;
		this.createdOn = createdOn;
	}

	public UserProjects(UserAccount userAccount, UserCategory userCategory, String projectName, String projectDesc,
			Date createdOn, String projectStatus, Double projectAmount, Date endDate, Double remainingAmount,
			Set userServiceses, Set projectDeleteReasons) {
		this.userAccount = userAccount;
		this.userCategory = userCategory;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
		this.createdOn = createdOn;
		this.projectStatus = projectStatus;
		this.projectAmount = projectAmount;
		this.endDate = endDate;
		this.remainingAmount = remainingAmount;
		this.userServiceses = userServiceses;
		this.projectDeleteReasons = projectDeleteReasons;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public UserCategory getUserCategory() {
		return this.userCategory;
	}

	public void setUserCategory(UserCategory userCategory) {
		this.userCategory = userCategory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	public Double getProjectAmount() {
		return this.projectAmount;
	}

	public void setProjectAmount(Double projectAmount) {
		this.projectAmount = projectAmount;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Double getRemainingAmount() {
		return this.remainingAmount;
	}

	public void setRemainingAmount(Double remainingAmount) {
		this.remainingAmount = remainingAmount;
	}

	public Set getUserServiceses() {
		return this.userServiceses;
	}

	public void setUserServiceses(Set userServiceses) {
		this.userServiceses = userServiceses;
	}

	public Set getProjectDeleteReasons() {
		return this.projectDeleteReasons;
	}

	public void setProjectDeleteReasons(Set projectDeleteReasons) {
		this.projectDeleteReasons = projectDeleteReasons;
	}

}
