package neu.edu.entity;
// Generated Apr 27, 2017 1:40:37 AM by Hibernate Tools 5.2.1.Final

/**
 * UserInformation generated by hbm2java
 */
public class UserInformation implements java.io.Serializable {

	private int userId;
	private UserAccount userAccount;
	private String lastName;
	private String address;

	public UserInformation() {
	}

	public UserInformation(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public UserInformation(UserAccount userAccount, String lastName, String address) {
		this.userAccount = userAccount;
		this.lastName = lastName;
		this.address = address;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
