package neu.edu.entity;
// Generated Apr 27, 2017 1:40:37 AM by Hibernate Tools 5.2.1.Final

/**
 * UserProject generated by hbm2java
 */
public class UserProject implements java.io.Serializable {

	private UserProjectId id;
	private UserAccount userAccount;
	private String description;

	public UserProject() {
	}

	public UserProject(UserProjectId id, UserAccount userAccount) {
		this.id = id;
		this.userAccount = userAccount;
	}

	public UserProject(UserProjectId id, UserAccount userAccount, String description) {
		this.id = id;
		this.userAccount = userAccount;
		this.description = description;
	}

	public UserProjectId getId() {
		return this.id;
	}

	public void setId(UserProjectId id) {
		this.id = id;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
