package neu.edu.entity;
// Generated Apr 27, 2017 1:40:37 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserCategory generated by hbm2java
 */
public class UserCategory implements java.io.Serializable {

	private Integer categoryId;
	private UserAccount userAccount;
	private String categoryName;
	private String categoryDesc;
	private String categoryStatus;
	private Set userProjectses = new HashSet(0);

	public UserCategory() {
	}

	public UserCategory(String categoryName) {
		this.categoryName = categoryName;
	}

	public UserCategory(UserAccount userAccount, String categoryName, String categoryDesc, String categoryStatus,
			Set userProjectses) {
		this.userAccount = userAccount;
		this.categoryName = categoryName;
		this.categoryDesc = categoryDesc;
		this.categoryStatus = categoryStatus;
		this.userProjectses = userProjectses;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public String getCategoryStatus() {
		return this.categoryStatus;
	}

	public void setCategoryStatus(String categoryStatus) {
		this.categoryStatus = categoryStatus;
	}

	public Set getUserProjectses() {
		return this.userProjectses;
	}

	public void setUserProjectses(Set userProjectses) {
		this.userProjectses = userProjectses;
	}

}
